# Generated by Django 3.2.17 on 2023-02-08 08:21
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('stu_name', models.CharField(max_length=100, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('stu_password', models.CharField(max_length=100, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('stu_gender', models.CharField(max_length=100, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
                ('stu_age', models.CharField(max_length=10, verbose_name=b'\xe5\xb9\xb4\xe9\xbe\x84')),
                ('stu_course', models.CharField(max_length=100, verbose_name=b'\xe7\xa7\x91\xe7\x9b\xae')),
                ('stu_score', models.IntegerField(default=0, verbose_name=b'\xe5\x88\x86\xe6\x95\xb0')),
                ('stu_nianji', models.CharField(max_length=100, verbose_name=b'\xe5\xb9\xb4\xe7\xba\xa7')),
                ('stu_xueqi', models.CharField(max_length=100, verbose_name=b'\xe5\xad\xa6\xe6\x9c\x9f')),
            ],
        ),
    ]
