# Generated by Django 3.2.17 on 2023-02-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生信息表'},
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_age',
            field=models.CharField(max_length=10, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_course',
            field=models.CharField(max_length=100, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_gender',
            field=models.CharField(max_length=100, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_nianji',
            field=models.CharField(max_length=100, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_score',
            field=models.IntegerField(default=0, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_xueqi',
            field=models.CharField(max_length=100, verbose_name='学期'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
